# Copyright (c) PLUMgrid, Inc.
# Licensed under the Apache License, Version 2.0 (the "License")

FROM fedora:rawhide

MAINTAINER Brenden Blanco <bblanco@plumgrid.com>

RUN dnf -y install bison cmake flex gcc gcc-c++ git libxml2-devel make python2-devel rpm-build wget zlib-devel

WORKDIR /root

RUN wget http://llvm.org/releases/3.7.1/{cfe,llvm}-3.7.1.src.tar.xz

RUN tar -xf llvm-3.7.1.src.tar.xz && mkdir llvm-